# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_title', models.CharField(max_length=200)),
                ('prob_description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prob_score', models.IntegerField()),
                ('prob_flag', models.CharField(max_length=100)),
                ('prob_image', models.ImageField(upload_to=b'')),
                ('prob_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
